#!/bin/bash

set -e

INSTALL_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $INSTALL_DIR

ZSHRC=~/.zshrc
OHMYZSH_DIR=~/.oh-my-zsh

EXTENSION_MARK=#--INSTALLER_EXTENSION--

function set_zshrc_param {
	REGEXP="^[[:space:]*#?[[:space:]]*$1=.*$"
	MUSTBE=$1=$2
	if grep -qP "$REGEXP" $ZSHRC; then
		sed -i "s|$REGEXP|$1=$2|g" $ZSHRC  
	else
		echo $MUSTBE >> $ZSHRC
	fi
}

function resolve {
	echo $1 | sed "s|\$INSTALL_DIR|$INSTALL_DIR|g"
}

function newline {
	echo "" >> $ZSHRC
}

# install ohmyszhs
if [ ! -e $OHMYZSH_DIR ]; then
	wget -O zsh_install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
	chmod +x ./zsh_install.sh
	pwd
	./zsh_install.sh
else
	echo "you ohmyzsh seems to be already installed. We will only update your .zshrc"
fi

###########################################################
# customize zsh with our options (overwriting if exists)  #
###########################################################
newline 
while read p; do
	RESOLVED=$(resolve "$p")
	set_zshrc_param $RESOLVED 
done < params.list

###############################################################
# start adding new options to .zshrc: first, remove old stuff #
###############################################################

# 0. remove everything after the mark and create it again (preventing repeated stuff)
newline
sed "/$EXTENSION_MARK/,\$d" $ZSHRC > zshrc.bak
rm $ZSHRC
mv zshrc.bak $ZSHRC
echo "$EXTENSION_MARK" >> $ZSHRC
echo "## This is generated by drozel's script $INSTALL_DIR/install.sh and can be overwritten on update. Please refer to comments in there."  >> $ZSHRC
echo "## Refer to https://github.com/drozel/linuxEnv for changes/help" >> $ZSHRC

# 1. add aliases (used directly from file)
newline
chmod +x $INSTALL_DIR/aliases.sh
echo ". $INSTALL_DIR/aliases.sh" >> $ZSHRC

# 2. add dynamic local aliases: all scripts in ~/.oh-my-zsh/aliases.rc will be called on runtime
newline
cat <<EOT >> $ZSHRC
if [ -e $OHMYZSH_DIR/aliases.rc ]; then
	for f in $OHMYZSH_DIR/aliases.rc ; do
		bash "$f" -H 
	done
fi
EOT

# 3. add plugins (just list plugins in plugins.inc)
newline
echo "plugins+=($(cat $INSTALL_DIR/plugins.inc))" >> $ZSHRC

# 4. link themes (just add your themes to themes/)
newline
for f in themes/*.zsh-theme
do
	ln -sf $(realpath $f) $OHMYZSH_DIR/$f 
done

# 5. add autoupdate (resticted to every N days)
newline
echo "$(realpath $INSTALL_DIR)/autoupdate.sh" >> $ZSHRC

# 6. include user's plain stuff
newline
cat plain.inc >> $ZSHRC
